### ISSUE TITLE
Soft spaces doesn't work

### ISSUE THREAD

**Issue by neomonkey** [atom/language-c#116]
The soft space settings doesn't work. I want to use 8 spaces as my indentation and the package doesn't allow this. With my settings below the indentation is random from 3-7.
```cson
"*":
  core:
    autoHideMenuBar: true
  editor:
    invisibles: {}
    softTabs: true
    tabLength: 8
```

**Comment by 50Wliu** [comment]
@neomonkey language-c does not control indentation.  Can you still reproduce your bug in safe mode (`atom --safe`)?

**Comment by neomonkey** [comment]
I opened the atom with the safemode at ubuntu 15.10 running under virtualbox. Yes it is repoducing at the safemode. Also I have an example how this works.

After:
#include line 8 spaces
function() line 7 spaces
function(){ line 6 spaces
while(){ line 2 spaces
pressing enter, no soft tabs...

And I just noticed that this seems to be a global problem. Even Javascript doesn't work, so if the package doesn't break anything I think this can be closed.

**Comment by 50Wliu** [comment]
I see you've commented over at atom/atom#10169, so I'll close this like you suggested :).
