### ISSUE TITLE
Handle C++11 raw strings properly

### ISSUE THREAD

**Issue by abyss7** [atom/language-c#117]
See http://en.cppreference.com/w/cpp/language/string_literal (6)

If there is `"` inside such string, then the colorifier doesn't work properly.

**Comment by infininight** [comment]
This has been added in the TextMate bundle if someone wants to port over the commit:

https://github.com/textmate/c.tmbundle/commit/022ffeb698bcb30ae89c459a4f11487ea4f5ecb8

**Comment by 50Wliu** [comment]
Thanks @infininight!
