### ISSUE TITLE
Difference between using `||` and `or`

### ISSUE THREAD

**Issue by omegahm** [atom/language-c#119]
In this example:

``` cpp
if (is_add_sub(instr.opcode) || is_mul_div(instr.opcode)) { ... }
if (is_add_sub(instr.opcode) or is_mul_div(instr.opcode)) { ... }
```

When using `||` both functions will be `support.function.any-method.c`, however when using `or` the second function gets `variable.other.c` scope instead.

![screen shot 2016-02-29 at 15 43 20](https://cloud.githubusercontent.com/assets/178448/13397760/a1c56aee-defb-11e5-9cee-4388e5b74d76.png)
![screen shot 2016-02-29 at 15 43 29](https://cloud.githubusercontent.com/assets/178448/13397759/a1c28f4a-defb-11e5-9863-32af882c0c61.png)

It even fails in the above markdown. :cry:

**Comment by thomasjo** [comment]
This is because `or` is not a valid C keyword, and the introduction of a variable in this expression is not valid. Hence the grammar doesn't handle this either.

**Comment by omegahm** [comment]
But this is C++ and C++ is selected as language. `or` is valid C++.

**Comment by thomasjo** [comment]
OK, then I agree that this seems like a bug in the grammar.

---
*For future reference, it would be helpful with more details such as the fact you were working with C++ and not C. Especially since the scope you provided alluded to this being C code.*
