### ISSUE TITLE
Operators like + , -, *, /, %, ^, |, &, ||, && Highlighting?

### ISSUE THREAD

**Issue by sidpagariya** [atom/language-c#123]
Is there any option to highlight operators like + , -, *, /, %, ^, |, &, ||, && in C++?

**Comment by Victorystick** [comment]
@green1139 What syntax theme are you using? The default `one-dark` theme doesn't highlight. Have you tried another theme?

**Comment by MaximSokolov** [comment]
No. See #114

**Comment by green1139** [comment]
@Victorystick I am making my own theme and so I wanted to know which code fragments I can use...

**Comment by Victorystick** [comment]
Oops. Looks like I spoke too soon.

**Comment by green1139** [comment]
#114 suggests that we can copy...is it ok to do so?
I want to highlight ALL possible operators and I think this might be possible...

**Comment by MaximSokolov** [comment]
_Some_ of the operators can be copied. I clarified my original comment in #114

**Comment by galactose310** [comment]
So concretely, I don't understand what is possible to do ? Idem for brackets and parenthesis, which are coloured as default text.
