### ISSUE TITLE
void main() function auto-complete problem.

### ISSUE THREAD

**Issue by ivmarkp** [atom/language-c#140]
I encountered this issue in C++ environment.
Auto-complete for `void main()` doesn't work like I expect it to be. Here's some snippets to help understand it better:

![void](https://cloud.githubusercontent.com/assets/17006136/15117511/79d332d0-1625-11e6-97b3-5aef7a5b6ca9.PNG)

Auto-complete suggests `main()` and when you press enter it inserts
 `int main(int argc, char const *argv[]) { /* code */ return 0; }`

![void main](https://cloud.githubusercontent.com/assets/17006136/15117518/84b3de52-1625-11e6-8d50-0a4d3fb6c9cc.PNG)

**Comment by 50Wliu** [comment]
The `main` autocompletion you're seeing is a snippet, which by default expands to what you see in the second image.  If you believe the `int` part should be configurable, then please open a new issue.  Thanks!

**Comment by ivmarkp** [comment]
Wouldn't it be more convenient to _not_ have `int`at all,  when `main` expands? In this case, I'd have to delete `int` because I wanted to use `void main()`.
