### ISSUE TITLE
C++11 Support

### ISSUE THREAD

**Issue by BigfootN** [atom/language-c#148]
Hello,

I am using monokai as syntax theme, and some keywords (such as nullptr) are not highlighted.

I know there are already several issues about this, but if, for example, #61 has been reopened ever since.

Thank you very much in advance :)

**Comment by 50Wliu** [comment]
As #61 mentioned, the lack of highlighting does not have to do with language-c but rather Monokai.  Please open a new issue on the Monokai repository.  Thanks!

**Comment by BigfootN** [comment]
Okay thank you, sorry for not reading more thoroughly, and thank you for your quick response :)
