### ISSUE TITLE
Printf Snippet Enhancement

### ISSUE THREAD

**Issue by AndrewSerie** [atom/language-c#150]
Printf Snippet Enhancement

**Steps**
1. Enter file "language-c/snippets/language-c.cson"
2. Find the "printf" snippet. Lines 56 - 58.
3. On line 58, Remove the ,(space) at the end of the snippet.
     - 58: 'body': 'printf("${1:%s}\\\\n", $2);$3'
     +58: 'body': 'printf("${1:%s}\\\\n"$2);$3'

**Current and suggested behavior**
Currently, I see that my compiler throws the error below:
/Users/andrewserie/Desktop/exp1.c:17:28: error: expected expression
  printf("Hello World!\n", );
1 error generated.

**Why would the enhancement be useful to most users**

Prevent compiler error.

**Screenshots and GIFs**

![screen shot 2016-05-31 at 1 16 29 pm](https://cloud.githubusercontent.com/assets/19672417/15685626/34ab7c12-2732-11e6-95a8-031c1b398d4b.png)

**Atom Version:** [1.7.4]
**OS and Version:** [OSX El Captain 10.11.4]

**Comment by AndrewSerie** [comment]
My apologies if this is not an issue or enhancement.  I am new to C.

**Comment by esdoppio** [comment]
@50Wliu Not sure about this, if you don't need interpolations or formatting, then you shouldn't use `printf` in the first place.
