### ISSUE TITLE
if define MACRO, c++ Syntax colorization and  highlighting is error

### ISSUE THREAD

**Issue by sridmad** [atom/language-c#152]
_From @sandy081 on June 16, 2016 8:24_

_From @shudingbo on June 15, 2016 10:50_
- VSCode Version: 1.2.1,maybe all version
- OS Version:  win,linux

Steps to Reproduce:
1.  no define macro, highlighting OK.

``` c++
DeskManagerImpl::DeskManagerImpl(){

}

DeskManagerImpl::~DeskManagerImpl(){

}

void DeskManagerImpl::SetDataInterface(){
    printf("%s success \n", __FUNCTION__);
}

void DeskManagerImpl::SetLogInterface(Nan::Persistent<v8::Function> *cbLog,
    Nan::Persistent<v8::Function> *cbLogDebug,
    Nan::Persistent<v8::Function> *cbLogData )
{
    _cbLog = cbLog;
    _cbLogDebug = cbLogDebug;
    _cbLogData = cbLogData;     
};
```
1. if define macro, **following, highlighting colorization all is macro's color**

``` c++
#define V8_GETATTR_INT(obj, name) (obj->Get(Nan::New( name ).ToLocalChecked()).As<v8::Integer>()->Value())
#define V8_GETATTR_STR(obj, name) (*Nan::Utf8String(obj->Get(Nan::New( name ).ToLocalChecked()).As<v8::String>()))

#define V8_ToString(obj,name,type) (*Nan::Utf8String( obj->Get(Nan::New( name ).ToLocalChecked()).As<type>()->ToString()))

//// The following, highlighting colorization all is macro's color
DeskManagerImpl::DeskManagerImpl(){

}

DeskManagerImpl::~DeskManagerImpl(){

}

void DeskManagerImpl::SetDataInterface(){
    printf("%s success \n", __FUNCTION__);
}

void DeskManagerImpl::SetLogInterface(Nan::Persistent<v8::Function> *cbLog,
    Nan::Persistent<v8::Function> *cbLogDebug,
    Nan::Persistent<v8::Function> *cbLogData )
{
    _cbLog = cbLog;
    _cbLogDebug = cbLogDebug;
    _cbLogData = cbLogData;     
};
```

_Copied from original issue: Microsoft/vscode#7714_

_Copied from original issue: Microsoft/vscppsamples#74_

**Comment by sridmad** [comment]
_From @smile4u on June 18, 2016 21:30_

I also discovered this problem. There is small workaround - if you add semicolon at the end of the last (or each) macro highlighting will be recovered

**Comment by sridmad** [comment]
Looks like a Textmate bundle issue. I see the exact issue in atom.

**Comment by 0xfeeddeadbeef** [comment]
Here's minimal repro:

```c++
#define my_macro other_macro(anything_enclosed_in_parentheses)

void foo(void)
{
    do_other_stuff();
}
```

In Atom, only `void foo(void)` is colored incorrectly.
In VSCode, entire function body gets "discolored".

In addition to incorrect colorization, this macro crashes VSCode C/Cpp Language Server every time it attempts to parse this snippet.
