### ISSUE TITLE
hexadecimal floating point numbers

### ISSUE THREAD

**Issue by GrandC** [atom/language-c#153]
floating point numbers can be written in hex like
0x7.Ap3
read as (hex)1.2 \* 2^3
but it is not recognized as a number in atom such as 0xE5, 10000, 1.5f which are all written in orange

**Comment by maxbrunsfeld** [comment]
This is fixed via https://github.com/tree-sitter/tree-sitter-c/commit/fd42e7588684cce690b4e3b9231c727206f80df5. The fix will go out in Atom 1.38.
