### ISSUE TITLE
and, or, ... keywords not highlighted

### ISSUE THREAD

**Issue by jhasse** [atom/language-c#157]
For readability it would great, if the keywords and, or, etc. are highlighted. See GitHub's highlighting as an example:

```cpp
if (a or b and c || d && e) {
}
```
(notice how ||, && aren't red here)

**Comment by 50Wliu** [comment]
`and` and `or` are properly highlighted using the C++ grammar (and those aren't valid in C).
See #123 for the && || variant.

**Comment by jhasse** [comment]
They aren't highlighted for me with Atom 1.9.8:
![bildschirmfoto vom 2016-08-15 16-33-10](https://cloud.githubusercontent.com/assets/80071/17667638/fb5ad754-6305-11e6-9838-b1cf4e85279e.png)

**Comment by 50Wliu** [comment]
That's an issue with your syntax theme (One Dark in this case).  For example, I'm using Fizzy and they're highlighted.

![fizzy](https://cloud.githubusercontent.com/assets/2766036/17667691/f162ef34-62d3-11e6-91b3-cec3f341f10f.png)

**Comment by jhasse** [comment]
Ah didn't know that, thanks :)
