### ISSUE TITLE
No Endif Directive 

### ISSUE THREAD

**Issue by handicraftsman** [atom/language-c#161]
There's no syntax highlight for #endif directive. Tested in C++.

**Comment by 50Wliu** [comment]
Cannot reproduce using 1.12.0-dev-4a73709.  Please supply a snippet here that reproduces the issue.

For reference, I tried
```c++
#if 0
#endif
```

**Comment by handicraftsman** [comment]
```c++
#ifndef _TEST_
  #define _TEST_

class test {
public:
  int just_for_test;
}

#endif
```
Lel. Here it doesn't highlighting too...

**Comment by hgdsraj** [comment]
your class must end with a semicolon, i.e.:

`#ifndef _TEST_
  #define _TEST_

class test {
public:
  int just_for_test;
};

#endif`

**Comment by hgdsraj** [comment]
Note the semicolon on `line 7`

**Comment by thomasjo** [comment]
Closing as `wontfix` since this is caused by invalid C++ syntax. The compiler in question might not complain (enough), but class (and struct) declarations must end with a semicolon.
