### ISSUE TITLE
C code coloring goes wrong after a line break backslash 

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#185]
_From @DanielKristofKiss on December 4, 2016 10:56_

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
---

Steps to Reproduce:
C source file content
```c
/* comment - green
 */
#define macro( arg ) \
        somerthingelse(arg)

/* comment - blue */

typedef int blueint;
typedef int whiteint;
```
![image](https://cloud.githubusercontent.com/assets/4526629/20865652/15599960-ba18-11e6-98b9-a27457ac68f9.png)

_Copied from original issue: Microsoft/vscode#16456_

**Comment by aeschli** [comment]
In Atom:
![image](https://cloud.githubusercontent.com/assets/6461412/20881712/f08e8188-badd-11e6-9189-52a89ae752f0.png)

Problem is caused by the scope 'meta.preprocessor.macro.c' that sticks around until line 10.

**Comment by 50Wliu** [comment]
```c
#define macro( arg ) \
        somethingelse(arg)

/* comment */

typedef int test1;
typedef int test2;
```
