### ISSUE TITLE
C Syntax Highlighting Bug

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#192]
Steps to Reproduce:

1. Use ternary operator in C
2. Put function in the "then" part
3. Syntax highlighting is wrong for that function (appears as a var)

_Copied from original issue: Microsoft/vscode#17942_

**Comment by aeschli** [comment]
_From @rebornix on December 30, 2016 18:52_

@brewsto can you try to disable c related extensions and then reload the window to see if it's caused by an extension?

**Comment by aeschli** [comment]
_From @pietz on December 30, 2016 18:58_

(this is brewsto)

its not caused by any extenstions, i disabled them all and checked again. same result. functions are not highlighted within the "then" part of a ternary operator.

**Comment by aeschli** [comment]
Reproduced with
```c
void main() {
    return f ? foo() : bar();
}
```
Same issue in Atom. The then part doesn't seem to be tokenised correctly.

**Comment by 50Wliu** [comment]
Was already fixed by #179.

**Comment by aeschli** [comment]
Thanks a lot @50Wliu !
