### ISSUE TITLE
Whitespace after pointer access operator breaks tokenizing and ligatures

### ISSUE THREAD

**Issue by laitdebanane** [atom/language-c#194]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using the pointer access operator in C/C++, if any whitespace is present right after the operator then the section of code is not properly tokenized. This is particularly visible when using ligatures.

### Steps to Reproduce

Type in the following code in a new file and activate syntax highlighting for C or C++:

```cpp
void f() {
  foo->bar;
  foo ->bar;
  foo-> bar;
  foo -> bar;
}
```

**Expected behavior:**

This is what the ligatures look like when using Plain Text syntax highlighting, and also what we expect them to look like with C/C++ syntax highlighting:

![image](https://cloud.githubusercontent.com/assets/22616578/21754194/7fdea808-d5fb-11e6-88a6-4e986dbf4796.png)

**Actual behavior:**

This is what the ligatures actually look like when using C or C++ syntax highlighting:

![image](https://cloud.githubusercontent.com/assets/22616578/21754211/1ab20a14-d5fc-11e6-8f91-e32303a7daa8.png)

**Reproduces how often:**

The issue seems to reproduce 100% of the time.

### Versions

Windows 10
Atom 1.12.9
Electron 1.3.13
Chrome 52.0.2743.82
Node 6.5.0
apm 1.12.9
npm 3.10.5
node 4.4.5
python 3.5.2
git 2.10.0.windows.1
visual studio

**Comment by 50Wliu** [comment]
Looks a bit related to #177.

**Comment by laitdebanane** [comment]
Pull request #195 fixed this issue.
