### ISSUE TITLE
Arrow in initializer list breaks syntax highlighting in C++

### ISSUE THREAD

**Issue by NOhs** [atom/language-c#198]
### Description

I was sent here from the C++ extension issue tracker of vscode. I don't know if this is the right place to post this, but when using the `->` operator in an initializer list in vscode C++ (which uses atom), the syntax highlighting gets mixed up.
![cpp_broken_syntax_highlighting](https://cloud.githubusercontent.com/assets/20553080/22301078/f1faf4b0-e329-11e6-93da-6c16b2f5c09f.PNG)

As you can see in the image above, the `c2`, the `6` and the `0.0f` are not highlighted.

![cpp_broken_syntax_highlighting_2](https://cloud.githubusercontent.com/assets/20553080/22301145/3d626f96-e32a-11e6-901b-45fa9e467cc7.PNG)

In the second picture the numbers are highlighted again after the second arrow was removed

![cpp_broken_syntax_highlighting_3](https://cloud.githubusercontent.com/assets/20553080/22301147/3faedf0a-e32a-11e6-93f9-09757a6b81db.PNG)

The syntax highlighting is correct after the first arrow is also removed.
### Steps to Reproduce

Insert the code in the above screenshot into the editor.

**Expected behavior:** code in initalizer list is properly highlighted

**Actual behavior:** code after `->` in initializer lists is not properly highlighted

**Reproduces how often:** 100%

### Versions

vscode 1.8.1 (I don't know which atom version that is)
OS: Arch Linux (fully updated 25.01.2017)

**Comment by 50Wliu** [comment]
```cpp
class X
{
    C<float> c1;
    C<float> c2;

    X(const Y y) :
        c1(y->get()),
        c2(y->get() * 6 + 0.0f)
    {
    }
};
```
Confirmed.

**Comment by DanielJamesCollier** [comment]
I am also having the same issue, happens with 1.9.1 and I am using "this->"
![c33c95287a62481c032a4081bbc6bb86](https://cloud.githubusercontent.com/assets/6226245/22626363/6a29e622-eba3-11e6-8ea5-98954baa727e.png)

**Comment by 50Wliu** [comment]
If you're using VSCode, you don't need to bother with the VSCode version.  Chances are that if it's broken in VSCode, it's broken in Atom as well.

Can you file a separate issue for your second picture as it happens without `->`?

**Comment by DanielJamesCollier** [comment]
@50Wliu yes, will file it now.

**Comment by 50Wliu** [comment]
This appears to have been fixed.
![image](https://cloud.githubusercontent.com/assets/2766036/23632952/cf11c19a-0291-11e7-945b-809a6a4f23b4.png)
