### ISSUE TITLE
Incorrect syntax highlighting of built-in types

### ISSUE THREAD

**Issue by DanielJamesCollier** [atom/language-c#201]
Version: 1.9.1
OS: macOS Sierra 10.12.2

please note that replacing "int" in this situation with any other built-in type will result in incorrect syntax highlighting.

<img width="188" alt="screen shot 2017-02-03 at 01 46 03" src="https://cloud.githubusercontent.com/assets/6226245/22576418/29ec1f54-e9b3-11e6-854e-6dc9c4a85d24.png">

<img width="197" alt="screen shot 2017-02-03 at 01 40 26" src="https://cloud.githubusercontent.com/assets/6226245/22576423/362337da-e9b3-11e6-8905-6faef0f16238.png">

```cpp
    int foo = 10;
    float bar = (int)foo; // first line
    float barz = int(foo); // second line
```

**Comment by alpyre** [comment]
This seems to have been fixed with #206
