### ISSUE TITLE
C++ custom class names not highlighted

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#207]
_From @Leedehai on February 12, 2017 5:45_

- VSCode Version: 1.9.1
- OS Version: macOS 10.12.3

Steps to Reproduce:

1. open a C++ file, type in:
```C++
class A {
private:
  int x;
public:
  A(int _x) {
	  x = _x;
  }
  A operator+(A &a) {
	  x++;
	  return *this;
  }
  A operator*(int c) {
	  x *= c;
	  return *this;
  }
  int get_value() {
	  return x;
  }
};

int main() {
	A a = A(1);
	return 0;
}
```
2. The class name "A" will not be highlighted the same way other built-in types (like "int") are, in lines like "A operator+(A &a)" and "A a = A(1)". But in Visual Studio custom class names are highlighted. 
3. Similar: #4948

_Copied from original issue: Microsoft/vscode#20500_

**Comment by aeschli** [comment]
The cpp grammar does not break up "A operator+(A &a)" and "A a = A(1)" in separate tokens.

**Comment by Leedehai** [comment]
Well.. does the VSCode team have plan for this issue? I really look forward to this. VSCode is a great editor!
I know it may be difficult to tackle, considering the class/struct/type definition may be in another file.. a lexer might be needed (plz ignore this if i am wrong:))

**Comment by LawrenceBuckingham** [comment]
If a fix is not forthcoming in the near future, is there any workaround?

**Comment by notAlaanor** [comment]
A solution is available as a workaround: https://github.com/cquery-project/cquery
Once configured correctly, the cquery extension for VSCode can provide semantic source highlighting and rapid code completion.

**Comment by maxbrunsfeld** [comment]
This is fixed if you use the new [Tree-sitter](http://tree-sitter.github.io/tree-sitter) parsing system, which is enabled by default in Atom 1.32 Beta. If you're not the beta channel, you can enable it by checking the `Use Tree-sitter Parsers` box in the settings view, or wait for Atom 1.32 Stable to be released. Thanks!
