### ISSUE TITLE
Syntax highlight for C code breaks with macro definition containing a function/parenthesis

### ISSUE THREAD

**Issue by mjbvz** [atom/language-c#211]
_From @mopsfelder on February 27, 2017 13:40_

- VSCode Version: 1.9.1
- Extensions: ms-vscode.cpptools@0.10.1
- OS Version: Fedora 25

Steps to Reproduce:

1. Create a basic C program with macro definition containing a function.  For example:

```c
#include <stdio.h>

#define FOO bar()

int main(void)
{
        return 0;
}
```
2. With the above code example, the syntax highlight for C code breaks, turning `main()` definition entirely blue-ish.  See:

![selection_032](https://cloud.githubusercontent.com/assets/2346907/23363321/e2961a36-fcd8-11e6-8c2e-236519a2f0c4.png)

It seems that the syntax highlight motor expects a comma `;` after a pair of parenthesis is added to macro definition, correcting the colors:

![selection_033](https://cloud.githubusercontent.com/assets/2346907/23363344/fcadf010-fcd8-11e6-8006-139170c84f0b.png)

_Copied from original issue: Microsoft/vscode#21493_

**Comment by mjbvz** [comment]
Confirmed this syntax highlighting issue in atom as well

**Comment by artagnon** [comment]
I think this is the same issue:

<img width="789" alt="screenshot 2017-03-01 20 19 12" src="https://cloud.githubusercontent.com/assets/37226/23488769/a72e1cb0-febc-11e6-993b-e0539b1926a3.png">
