### ISSUE TITLE
Cannot change format specifier color when syntax is C++

### ISSUE THREAD

**Issue by ooJerryLeeoo** [atom/language-c#226]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Cannot change format specifier color when syntax is `C++`

### Steps to Reproduce

1. Add these code into `styles.less`:

``` less
.syntax--source.syntax--c,
.syntax--source.syntax--cpp {
  .syntax--constant.syntax--other.syntax--placeholder {
    color: white; // or other color
  }
}
```
2. Open a file
3. Add these code into the file

``` c++
#include <stdio.h>

int main() {
  printf("%d");
}
```

4. Set the syntax to `C++`
5. The `%d` color is not change
6. Change the syntax to `C`
7. The `%d` color is change to white

**Expected behavior:** the format specifier color should be change either syntax is `C` and `C++`

**Actual behavior:** the format specifier color only change when the syntax `C`.

Example:

`C++`

![cpp](https://cloud.githubusercontent.com/assets/20783502/24873717/8a317104-1e54-11e7-921a-5577c15e8d3e.png)

`C`

![c](https://cloud.githubusercontent.com/assets/20783502/24873720/8db26a0e-1e54-11e7-9b43-fcf6749cb751.png)

### Versions

`Atom`: `1.17.0-beta2`  
`OS`: `macOS sierra`

**Comment by ooJerryLeeoo** [comment]
@50Wliu Can you take a look ??

**Comment by ooJerryLeeoo** [comment]
@50Wliu Can you take a look ??

**Comment by 50Wliu** [comment]
Confirmed.

**Comment by ooJerryLeeoo** [comment]
@50Wliu Any update in this ?

**Comment by 50Wliu** [comment]
No.
