### ISSUE TITLE
Keyword highlighting in inheritance list breaks after a new line

### ISSUE THREAD

**Issue by sean-mcmanus** [atom/language-c#232]
Reproed with VS Code - Insiders (they're on the April 7th version). Seems related to https://github.com/atom/language-c/issues/101 .

class b {};
class c {};
class a: public b,
	public c
{};
![image](https://cloud.githubusercontent.com/assets/19859882/25255151/21a2b5e4-25de-11e7-94b5-aa268a95cb86.png)

**Comment by bobbrow** [comment]
A similar report (copied from https://github.com/Microsoft/vscode-cpptools/issues/748)
@Vultraz

Inherited class names aren't highlighted correctly if they're on a new line

![class formatting issue](https://cloud.githubusercontent.com/assets/3558659/26288042/2f626a58-3ed4-11e7-9bd8-d0acaab6f751.JPG)

Virtual keyword in inheritance takes the class name highlighting.

![class formatting issue2](https://cloud.githubusercontent.com/assets/3558659/26288057/9bb59ba8-3ed4-11e7-9318-bdd9214a1074.JPG)

**Comment by maxbrunsfeld** [comment]
This is fixed if you use the new [Tree-sitter](http://tree-sitter.github.io/tree-sitter) parsing system, which is enabled by default in Atom 1.32 Beta. If you're not the beta channel, you can enable it by checking the `Use Tree-sitter Parsers` box in the settings view, or wait for Atom 1.32 Stable to be released. Thanks!

**Comment by bobbrow** [comment]
This issue is about the TextMate grammar as we consume it in VS Code, so we can't just switch to Atom 😉 .  Are you essentially saying that the old grammar will not be updated and that VS Code needs to use this new tree-sitter thing instead of TextMate now?

**Comment by maxbrunsfeld** [comment]
We'll continue to accept PRs that update the text-mate grammar for quite a while probably, but we probably won't prioritize work on these kinds of things ourselves, since Atom is moving away from TextMate for this language.

I'm closing this one out because the bug is fixed on Atom's end by switching grammars, and the Atom team uses issues as a kind of backlog - to keep track of work that we still need to do.
