### ISSUE TITLE
the comment   /*  …… */    can not be nested.

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#248]
_From @eillon on June 18, 2017 8:21_

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:18:03.540Z)
- OS Version: Linux x64 4.8.0-54-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-runner|formulahendry|0.6.20|
|cpptools|ms-vscode|0.11.4|;

---

Steps to Reproduce:
Such as this:
![image](https://user-images.githubusercontent.com/18638530/27259301-0cbf17e8-5442-11e7-823c-f34df79bdc0c.png)

_Copied from original issue: Microsoft/vscode#28954_

**Comment by aeschli** [comment]
_From @CherryDT on June 18, 2017 8:40_

@eillon Which language are you refering to? I don't know any programming language so far where nested `/* */` is allowed, so it would be correct that VSCode tells you this.

EDIT: Okay now I know one, called "Newspeak". Still, none of the _major_ languages I know support it.

**Comment by aeschli** [comment]
_From @eillon on June 18, 2017 10:9_

@CherryDT  C and C++. I can compile and run the program corrently, but the VSCode tells me it's wrong.

**Comment by aeschli** [comment]
_From @CherryDT on June 18, 2017 19:27_

@eillon What compiler are you using? To all my knowledge, neither C nor C++ support this.

**Comment by aeschli** [comment]
_From @eillon on June 19, 2017 8:5_

@CherryDT  gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
you can try the program below:
`#include<stdio.h>
int main(){   
    printf("Hello World\n");  
    /* /*  */ */     
    return 0;  
}`
It can compile and run corrently, but VSCode may give a red point-out.

**Comment by CherryDT** [comment]
@eillon
Not sure how you managed to do that, with the same compiler version I get an error just as I would expect:

![image](https://user-images.githubusercontent.com/6010463/29217489-4131d066-7eb2-11e7-9378-79ccfd6da80d.png)

**Comment by 50Wliu** [comment]
Closing as `wontfix`.  The majority of C compilers do not support nested comments.
