### ISSUE TITLE
Incorrect highlighting when source.c or source.cpp is embedded within another grammar

### ISSUE THREAD

**Issue by mjbvz** [atom/language-c#250]
From https://github.com/Microsoft/vscode/issues/34525

### Description

When the c/cpp grammar is embedded within another grammar, the syntax highlighting is incorrect. A simple example is the markdown grammar which embeds `source.c` and `source.cpp` for highlighting fenced code blocks

### Steps to Reproduce

1. In a markdown file write: 
~~~md
```c
int foo() {
  int bar = 1
}
```
~~~

**Expected behavior:** [What you expect to happen]
Contents of `foo` are syntax colored.

**Actual behavior:** [What actually happens]
`int bar` is scoped as markdown and not colored

<img width="643" alt="screen shot 2017-09-18 at 9 44 46 am" src="https://user-images.githubusercontent.com/12821956/30553427-0a418990-9c56-11e7-8d48-3553795e63e5.png">

**Cause**

The root cause is that the c/cpp grammars use `$base`. When embedded, this resolves to the root grammar which is markdown in this case. 

See https://github.com/textmate/c.tmbundle/pull/44 / https://github.com/textmate/textmate/pull/1276

**Comment by 50Wliu** [comment]
See #146.  Textmate handles `$base` poorly when embedded.
