### ISSUE TITLE
and, or, ... not colored as keywords

### ISSUE THREAD

**Issue by jhasse** [atom/language-c#258]
`and`, `or` aren't colored as keywords, which results in them not being easily distinguishable in VS Code. See https://github.com/Microsoft/vscode/issues/28555

**Comment by thomasjo** [comment]
They are captured as [keywords](https://github.com/atom/language-c/blob/master/grammars/c%2B%2B.cson#L72-L73). This ultimately seems like something that needs to be resolved in VS Code, since we're correctly marking them as keywords, specifically `keyword.operator.cpp`.
