### ISSUE TITLE
[cpp] syntax highlighting in type declarations

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#266]
I've noticed that for C++ source codes, the color formatting of the 'Type' in declarations (e.g. string x; User_defined_type y; etc. etc) is the same as the default font styling. 

```cpp
#include <string>

using namespace std;

int main() {
	string x;
}
```

_Copied from original issue: Microsoft/vscode#46831_

**Comment by maxbrunsfeld** [comment]
This is fixed if you use the new [Tree-sitter](http://tree-sitter.github.io/tree-sitter) parsing system, which is enabled by default in Atom 1.32 Beta. If you're not the beta channel, you can enable it by checking the `Use Tree-sitter Parsers` box in the settings view, or wait for Atom 1.32 Stable to be released. Thanks!
