### ISSUE TITLE
When tree-sitter parsers are enabled, ".h" files are treated as C headers by default.

### ISSUE THREAD

**Issue by dogancan** [atom/language-c#268]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Currently ".h" files are treated as C++ headers by default. [The new tree-sitter grammars for both C and C++ list ".h" extension among the recognized file types](https://github.com/atom/language-c/blob/master/grammars/tree-sitter-c.cson#L8) which results in ".h" files being treated as C headers by default. Also, overriding the default grammar assignment in `~/.atom/config.cson` using the `core.customFileTypes` property (as below) does not work when tree-sitter parsers are enabled.

```
"*":
  core:
    customFileTypes:
      "source.cpp": [ "h" ]
  # ...
```

### Steps to Reproduce

1. Enable the “Use Tree Sitter Parsers” setting in Atom’s core settings.
2. Open a file with ".h" extension.

**Expected behavior:** The file is recognized as a C++ header.

**Actual behavior:**  The file is recognized as a C header.

**Reproduces how often:** 100%

### Versions

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
OS        : MacOS 10.13.3

**Comment by thomasjo** [comment]
Simply change `source.cpp` to `cpp`, and everything should work as expected.

**Comment by dogancan** [comment]
Thanks!

**Comment by Ben3eeE** [comment]
Looks like this was resolved.
