### ISSUE TITLE
Cpp code highlighting borken by opening and closing brackets in different preprocessor blocks

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#275]
_From @ItBeLab on May 4, 2018 6:23_

It is possible to break syntax highlighting by opening and closing brackets in different preprocessor blocks

![image](https://user-images.githubusercontent.com/37258512/39614960-8e590116-4fae-11e8-8b58-755aeceb5f4b.png)

_Copied from original issue: Microsoft/vscode#49174_

**Comment by Arcanemagus** [comment]
Here's the code:
```cpp
void foo(std::function<void()> lambda)
{
    lambda();
}

void bar()
{
#if 1
    foo( // <- this bracket is the troublemaker
        []
        ()
        {
#endif

#if 1
        }
    );
#endif
}
```

Using Atom v1.27.0-beta1 it looks like I can reproduce this:
![image](https://user-images.githubusercontent.com/427137/39650312-862a22f2-4f9c-11e8-816b-6813ec0d0298.png)

Note that the only part that seems to be parsed incorrectly is the `#endif` as it recovers immediately after that from what I can tell.

**Comment by maxbrunsfeld** [comment]
This is fixed if you use the new [Tree-sitter](http://tree-sitter.github.io/tree-sitter) parsing system, which is enabled by default in Atom 1.32 Beta. If you're not the beta channel, you can enable it by checking the `Use Tree-sitter Parsers` box in the settings view, or wait for Atom 1.32 Stable to be released. Thanks!
