### ISSUE TITLE
`meta.function-call` sticks around after `(int)::`

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#276]
```c
int Whatever1()
{
    return (int)::Whatever2();
}
int Whatever3()
{
}
```

After `(int)::` a `meta.function-call` is pushed and sticks around, causing that `Whatever3` gets a variable scope.

**Comment by Arcanemagus** [comment]
Confirming on `1.31.0-nightly9`:
![image](https://user-images.githubusercontent.com/427137/44388881-26799f80-a4de-11e8-8a79-5fd697340f00.png)

**Comment by maxbrunsfeld** [comment]
This is fixed if you use the new [Tree-sitter](http://tree-sitter.github.io/tree-sitter) parsing system, which is enabled by default in Atom 1.32 Beta. If you're not the beta channel, you can enable it by checking the `Use Tree-sitter Parsers` box in the settings view, or wait for Atom 1.32 Stable to be released. Thanks!
