### ISSUE TITLE
simmilar function calls get different scopes

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#278]
From https://github.com/Microsoft/vscode/issues/50081:

As you can see in the image, two **pow** functions are green but the last one is blue. It's caused by different scopes. The one odd `pow` has `support.function`, the others are `entity.name.function`

![image](https://user-images.githubusercontent.com/8548534/40216120-fe5d95bc-5a3a-11e8-8170-731ac1e452cd.png)
```
unsigned long long int uint62to10_ (const char* str_) {
    unsigned long long int aux = 0;
    unsigned char aux_ = strlen(str_);
    while ( *str_ ) {
        ((*str_ - 0) > 96) ? 
            (aux += (9 + ((*str_++ - 0) - (96 - 26))) * pow(62, --aux_)) :
            ( ((*str_ - 0) > 64) ? (aux += (9 + ((*str_++ - 0) - 64)) * pow(62, --aux_)) : (aux += ((*str_++ - 0) - 48) * pow(62, --aux_)) ); 
    }
    return aux;
}
```

**Comment by maxbrunsfeld** [comment]
This is fixed if you use the new [Tree-sitter](http://tree-sitter.github.io/tree-sitter) parsing system, which is enabled by default in Atom 1.32 Beta. If you're not the beta channel, you can enable it by checking the `Use Tree-sitter Parsers` box in the settings view, or wait for Atom 1.32 Stable to be released. Thanks!
