### ISSUE TITLE
C/C++ grammar does not properly recognize a defines with a comment it in

### ISSUE THREAD

**Issue by alexr00** [atom/language-c#307]
_From @ZCShou on November 16, 2018 5:28_

#define IS_UPGRADE_ADDR(addr)					(/*((addr) >= UPGRADE_BASE_ADDR) && */(addr) < UPGRADE_BASE_ADDR + UPGRADE_SPACE_SIZE)

The code after the comments is only classified as source.c

![image](https://user-images.githubusercontent.com/38270282/48613856-224e0880-e98d-11e8-8782-2f823190bd3c.png)

_Copied from original issue: Microsoft/vscode#63273_

**Comment by maxbrunsfeld** [comment]
This only affects the TextMate parser; it's not a problem for the Tree-sitter parser.
