### ISSUE TITLE
Passing compound literals as function parameter breaks highlighting

### ISSUE THREAD

**Issue by nigolaj** [atom/language-c#312]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Passing compound literals as function parameter breaks highlighting
![out](https://user-images.githubusercontent.com/39564397/49468403-183d5e00-f805-11e8-9d7d-41330c0f8db3.gif)

Reduced example:
```
int main(int argc, char const *argv[]) {
  char const *p = "variable just for example";
  printf((char const[]){'a', 'b', 'c', '\n'});
  int another_variable = 3;
  return 0;
}
```
Tested with default Atom themes.

*Edit by @rsese to add additional screenshot, `syntax--c` missing in the first screenshot*

![no-syntax-c](https://github-slack.s3.amazonaws.com/monosnap/test.c__worktest-tree-sitter_2018-12-05_01-02-27.png)

With that line commented out:

![syntax-c](https://github-slack.s3.amazonaws.com/monosnap/test.c__worktest-tree-sitter_2018-12-05_01-04-09.png)

### Versions

Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0
python 2.7.15
git 2.19.2

Latest Solus

**Comment by rsese** [comment]
Thanks for the report!  Reproduced on macOS 10.12.6 with 1.33.0.

![no-syntax-c](https://github-slack.s3.amazonaws.com/monosnap/test.c__worktest-tree-sitter_2018-12-05_01-02-27.png)

With that line commented out:

![syntax-c](https://github-slack.s3.amazonaws.com/monosnap/test.c__worktest-tree-sitter_2018-12-05_01-04-09.png)

**Comment by maxbrunsfeld** [comment]
Thanks for the report! This will ship in Atom 1.38.
