### ISSUE TITLE
C++ class member function with attribute specifier and trailing return type breaks all following syntax highlighting if it is in a templated class

### ISSUE THREAD

**Issue by Josh-Thompson** [atom/language-c#313]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This seems like a corner case situation.

With a templated Foo, an attribute, and trailing return type, the highlighting in Bar is broken:

*Edit by @rsese for easy copy/paste*

```cpp
namespace test {

  template<typename T>
  class Foo {

    int x;

    [[nodiscard]] auto getX() -> int {

      return x;
    }
  };

  template<typename T>
  class Bar {

    int x;
    float y;

  };
}
```

![image](https://user-images.githubusercontent.com/29376852/50263824-bcb6c700-03e5-11e9-99bc-257e547fd197.png)

With a non-templated Foo, an attribute, and a trailing return type, Bar is fine:
![image](https://user-images.githubusercontent.com/29376852/50263849-d48e4b00-03e5-11e9-85f9-985ff4a6d5b6.png)

With a templated Foo, an attribute, and no trailing return type, Bar is also fine:
![image](https://user-images.githubusercontent.com/29376852/50263874-f2f44680-03e5-11e9-876e-5e936d3768c4.png)

### Steps to Reproduce

The above example will always reproduce the condition.

**Expected behavior:** Syntax highlighting for following classes behaves as normal

**Actual behavior:** Syntax highlighting is not normal

**Reproduces how often:** Always

### Versions

language-c: 0.60.13
Atom    : 1.33.1
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.1
python 2.7.15
git 2.17.1.windows.2

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce with 1.33.1 on macOS 10.12.6.
