### ISSUE TITLE
Scientific number notation not recognised / scoped correctly with tree-sitter

### ISSUE THREAD

**Issue by binaryfunt** [atom/language-c#323]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

E-notation numbers (i.e. scientific / engineering notation) are not highlighting correctly with tree-sitter because they are receiving different scopes for the first number, the "e", the "-" or "+", and the power.

![Screenshot (28)](https://user-images.githubusercontent.com/14579418/54196089-53ac9000-44b8-11e9-9380-8720df9d6f85.png)

![Screenshot (29)](https://user-images.githubusercontent.com/14579418/54196100-58714400-44b8-11e9-804e-ed1706dfae0c.png)

It doesn't matter if the "e" is uppercase or lowercase.

### Versions

Atom: 1.35.0
Electron: 2.0.18
Windows: 10 v1803

### Additional Information

For comparison, e-notation numbers in e.g. JavaScript are highlighted correctly (scope `constant.numeric`), if that's useful info.

**Comment by rsese** [comment]
Thanks for the report!  Reproduced with 1.37.0-nightly12 on macOS 10.12.6.  With Tree-sitter disabled:

![tree-sitter-disabled](https://github-slack.s3.amazonaws.com/monosnap/test.c__worktest-tree-sitter_2019-03-13_21-03-49.png)

**Comment by maxbrunsfeld** [comment]
Thanks for the report! This will ship in Atom 1.38.
