### ISSUE TITLE
Backslash in a single comment messes up the syntax highlighting.

### ISSUE THREAD

**Issue by marehr** [atom/language-c#327]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Backslash `\` in a single comment messes up the syntax highlighting.

### Steps to Reproduce

* Enable tree-sitter
* Open a `.cpp` file.
* Paste
   ```c++
   //aa \a dsadsa dsadsa dsa dsa dsa dasd
   void hello();
   ```

![Screenshot from 2019-05-09 13-54-07](https://user-images.githubusercontent.com/103778/57452872-2afd0880-7265-11e9-8e65-1406edfc14e4.png)

This makes the source code really hard to read. For example if you use doxygen with the `\` notation,`//!\brief A really long informative comment` becomes distracting.

**Expected behavior:** Just highlight the first word following `\` and show the rest as comment.

**Actual behavior:** Weird highlighting after the first escaped word.

**Reproduces how often:** :100:

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
language-c: 0.60.14

atom --version
Atom    : 1.36.1
Electron: 4.1.4
Chrome  : 69.0.3497.128
Node    : 10.11.0
apm  2.1.7

apm --version
npm  6.9.0
node 11.15.0 x64
atom 1.36.1
python 2.7.16
git 2.21.0
```

### Additional Information

I think this is a regression, because this did not happen in an earlier version.

//EDIT:
This seems to be a tree-sitter problem. Turning it off will resolve this issue.

**Comment by rsese** [comment]
Thanks @marehr - reproduced with 1.38.0-nightly21 on macOS 10.12.6 and also see it works ok with Tree-sitter disabled.

**Comment by Ben3eeE** [comment]
Seems like https://github.com/tree-sitter/tree-sitter-c/pull/17 could fix this issue.

**Comment by marehr** [comment]
I think so too! Thank you for sharing!

**Comment by theslyprofessor** [comment]
This is a Newb question, but how do I turn off tree sitter in the Atom package Language-C?

**Comment by marehr** [comment]
Go to Settings Packages -> Settings view -> Open, then go to Core and at the bottom find the checkbox "Use Tree Sitter Parsers". Uncheck it.

**Comment by maxbrunsfeld** [comment]
This is fixed on master.
