### ISSUE TITLE
Template Class Constructor Incorrect Highlighting

### ISSUE THREAD

**Issue by BeefaloKing** [atom/language-c#332]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Both the name and initializer list of template class constructors have incorrect syntax highlighting when defined outside the class declaration.
![image](https://user-images.githubusercontent.com/9630438/59861089-69461700-933d-11e9-9809-4300e55b13c9.png)
Edit: Added clarity in screenshot

### Steps to Reproduce

1. Define a constructor for a template class outside the class declaration
```
template<typename T> class foo
{
public:
	foo();
private:
	T *data;
};

class bar
{
public:
	bar();
private:
	int *data;
};

template<typename T> foo<T>::foo() : data(nullptr)
{}

bar::bar() : data(nullptr)
{}
```

### Versions

Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Possible Related Issues

https://github.com/atom/language-c/issues/90

**Comment by rsese** [comment]
Thanks for the report!  Noting I see the same thing as your screenshot in 1.40.0-nightly10 on macOS 10.12.6.

> Both the name and initializer list of template class constructors have incorrect syntax highlighting when defined outside the class declaration.

Just so I'm on the same page, can you point to exactly where this is in your example?

**Comment by BeefaloKing** [comment]
The `foo()` and `data(nullptr)` on line 17.  These should match the highlighting for the constructor `bar()` on line 20.

Additionally, if `foo()` were not a constructor, and had a return type, it would be highlighted correctly. (e.g. `template<typename T> int foo<T>::foobar()`)

**Comment by rsese** [comment]
Heyo @maxbrunsfeld :wave:!  We talked about this one today and think it might belong in https://github.com/tree-sitter/tree-sitter-cpp but were wondering if you could confirm?

**Comment by maxbrunsfeld** [comment]
> think it might belong in https://github.com/tree-sitter/tree-sitter-cpp but were wondering if you could confirm?

Yup, you're right: we currently don't parse those template constructors correctly. Thanks!

**Comment by BeefaloKing** [comment]
Should I create a separate issue over there or is this (part of) an already known issue?

**Comment by rsese** [comment]
ahh sorry, missed your comment @BeefaloKing - I went ahead and copied over your issue so we'll close this in favor of that issue: https://github.com/tree-sitter/tree-sitter-cpp/issues/50.
