### ISSUE TITLE
syntax/grammar color broke with 'operator'

### ISSUE THREAD

**Issue by sylvere-k** [atom/language-c#356]
I noticed that you can't type "operator+" when I wan't to overload an operator in a custom class (or anything like that) else "operator" and the '+' sign won't be colored as they should.
The only way to have them colored the right way is to separate them with spaces "operator + ", which is awful but could be fine IF it didn't broke the color/grammar/syntax of the rest of the function/etc :
when doing so, "const" won't be his normal color, and "return" either.
![tmpgithubissue](https://user-images.githubusercontent.com/55602912/96164210-31dc8000-0f1b-11eb-92d4-93958c338125.png)
![tmpgithubissue1](https://user-images.githubusercontent.com/55602912/96164212-32751680-0f1b-11eb-8fbf-7e4fe6bd99f3.png)
Here's the screenshots.
I can also give the whole source code if needed.

Thanks !

**Comment by CPterion** [comment]
### More details:
The highlighting error is fixed when `>` is added.
![No >](https://user-images.githubusercontent.com/71970115/114286251-9ffb9d00-9a8f-11eb-994d-cf085b9d7539.png)
![With >](https://user-images.githubusercontent.com/71970115/114286252-a0943380-9a8f-11eb-8257-e98d9216bc9c.png)

Also, the following code has a problem:
```
bool operator , (const Nbcomplexe & b) const {
	return (mod() > b.mod());
}
```

The highlighting error is partially fixed when a non-whitespace is added.
**Alphanumeric**
![Alphanumeric](https://user-images.githubusercontent.com/71970115/114286246-970acb80-9a8f-11eb-8efd-92c4e73cd29e.png)
**Number**
![Number](https://user-images.githubusercontent.com/71970115/114286244-95d99e80-9a8f-11eb-9680-2d7077c8337b.png)
**Opening Parenthesis**
![Opening Parenthesis](https://user-images.githubusercontent.com/71970115/114286248-97a36200-9a8f-11eb-918e-b328111f2ebd.png)

```
bool operator > (const Nbcomplexe & b) const {
	return (mod() > b.mod());
}
bool operator < (const Nbcomplexe & b) const {
	return (mod() > b.mod());
}
bool operator , (const Nbcomplexe & b) const {
	return (mod() > b.mod());
}
```
I tested this code and the syntax highlighting works for TextMate, both the highlighting on operator without spaces and when `<` or `,` is used.
**Tree-sitter**
![Tree-sitter](https://user-images.githubusercontent.com/71970115/114286191-24015500-9a8f-11eb-84be-229635d74fe1.png)
**TextMate**
![TextMate](https://user-images.githubusercontent.com/71970115/114286203-43987d80-9a8f-11eb-9d64-1b5421928f4f.png)
![TextMate no spaces](https://user-images.githubusercontent.com/71970115/114286207-45624100-9a8f-11eb-8349-5b0c6edfa313.png)

**Comment by chbk** [comment]
Looks like this is a Tree-sitter issue. You should post it here: https://github.com/tree-sitter/tree-sitter-cpp/issues

**Comment by chbk** [comment]
Mentioned here: https://github.com/tree-sitter/tree-sitter-cpp/issues/110
