### ISSUE TITLE
Type names of form "sometype_t" lose syntax highlighting with capitalization.

### ISSUE THREAD

**Issue by stuthedew** [atom/language-c#45]
So maybe this is just a convention that I am not familiar with, but I've noticed something weird (at least to me) about Atom's C syntax highlighting.
Specifically, type names ending with "_t" are only highlighted if all letters are lowercase. For example:
```c
lettercase_t foo1; // "lettercase_t" is highlighted by Atom.

letterCase_t foo2; // "letterCase_t" is not highlighted by Atom.
```
I've just noticed that it does the same thing here after posting the above example. Is this a bug or just expected behavior?

Thanks!

**Comment by vladimir-didenko** [comment]
There are several related problems.

1. Variable that ends with _t is highlighted as type e.g.

```C
int var_t;
```

2. Non standard types that are not ended with _t are not highlighted at all e.g.

```C
MYTYPE *fh;
```

**Comment by ear** [comment]
I hope this is right but let me ask: should this have prevented the error in highlighting in these cases I have today? Here are some screenshots:

![screen shot 2016-01-14 at 21 35 04](https://cloud.githubusercontent.com/assets/2104122/12336852/f31f3bae-bb06-11e5-8cc3-b2b5722bbcd1.png)
![screen shot 2016-01-14 at 21 35 26](https://cloud.githubusercontent.com/assets/2104122/12336853/f57949ee-bb06-11e5-803e-616d07afe027.png)

I.e. `size_t` and `<cstdint>`/ `<stdint.h>` types like `uint64_t`.

I guess it bears mentioning I am in a `.cpp` file. Atom is just using this `language-c` package, no other relevant ones.

**Comment by 50Wliu** [comment]
@ear Your syntax theme might not support C that well.  Can you please click right before `size_t` and execute the `Editor: Log Cursor Scope` command?  Thanks!

**Comment by ear** [comment]
Sure thing! Here it is:
```
Scopes at Cursor

source.cpp
support.type.sys-types.c
```

**Comment by 50Wliu** [comment]
Ok, that means that language-c is picking them up correctly.  You might want to file an issue with Atom Gooey asking them to highlight `support.type.sys-types`.
