### ISSUE TITLE
Certain keywords not being highlighted

### ISSUE THREAD

**Issue by thehutch** [atom/language-c#61]
The following C++ keywords are not being highlighted in Atom:

* nullptr
* this
* constexpr
* throw
* noexcept

Here are some screenshots of some of the keywords:

![Nullptr](https://dl.dropboxusercontent.com/u/38714192/nullptr.png)
![NoExcept & Throw](https://dl.dropboxusercontent.com/u/38714192/noexcept_throw.png)

**Comment by kevinsawicki** [comment]
Does the status bar say `C++` or `C` for the file being edited? Just want to make sure the right grammar is being used.

**Comment by thehutch** [comment]
In the bottom right hand corner, it says C++.

**Comment by thehutch** [comment]
Ah, I found the issue. It's not to do with language-c but instead with Monokai. I tested with other themes and they all highlight correctly.

**Comment by jbreitbart** [comment]
noexcept is not highlighted for me regarding which syntax theme I use. The other ones named in the original bug report are fine, however. Status bar reports C++

**Comment by mnquintana** [comment]
@jbreitbart Would you mind opening a separate issue for that?
