### ISSUE TITLE
C++11: noexcept not highlighted

### ISSUE THREAD

**Issue by jbreitbart** [atom/language-c#78]
In C++ code the qualifier noexcept is not highlighted correctly. I have tried various syntax themes

Here is an example code:

``` C++
class a {
    void f() noexcept {
    }
};
```

![noexecpt](https://cloud.githubusercontent.com/assets/881727/8396325/6fda2996-1da1-11e5-806d-4cbad3020f26.png)

**Comment by jamesqo** [comment]
Fixed by #131

**Comment by 50Wliu** [comment]
This actually has not been fixed.
