### ISSUE TITLE
Function pointers declaration as parameters break highlighting

### ISSUE THREAD

**Issue by nathansizemore** [atom/language-c#82]
<img width="470" alt="screen shot 2015-07-24 at 11 14 21 am" src="https://cloud.githubusercontent.com/assets/3423825/8877813/73fe8522-31f5-11e5-9162-7e0c1965be9b.png">

**Comment by alekulyn** [comment]
Same thing with declaring normal function pointers:
```c
char *(*webhook_put)(char *idWebhook);
```

**Comment by 50Wliu** [comment]
Seems to have been fixed.  I can't reproduce on Atom 1.15.0-dev-d5785a1 using the following code snippet:
```c
void test()
{
    int connect(const char *address,
                void (*data_received)(const char *, const int len),
                void (*on_connect)(),
                void (*on_disconnect)());
}
```
