### ISSUE TITLE
Weird C++ syntax highlighting (for-loop)

### ISSUE THREAD

**Issue by laituan245** [atom/language-c#98]
Why is the variable name 'fIndex' colored red while 'eIndex' and 'dIndex' are colored white ?

![selection_031](https://cloud.githubusercontent.com/assets/3805149/10716662/64c4d368-7b83-11e5-9205-434b3e2543ab.png)

**Comment by 50Wliu** [comment]
Because of this rule: https://github.com/atom/language-c/blob/master/grammars/c%2B%2B.cson#L46-L48

**Comment by Victorystick** [comment]
Urgh! :stuck_out_tongue:

**Comment by thedaniel** [comment]
I'm going to close this as "won't fix", because (I believe) this highlighting pattern came from TextMate and is not uncommon in other editors. Sorry that it doesn't look nice in your code example!
