### ISSUE TITLE
Add full support for C++11/14 syntax

### ISSUE THREAD

**Issue by fbbdev** [atom/language-c#99]
The syntax highlighter is confused by raw strings when they contain quotes, and some other quirks show up sometimes. Best solution at the moment is to install [jbw3/language-cpp14](https://github.com/jbw3/language-cpp14), but this forces me to put `-*- C++14 -*-` in my source files, breaking other editors.

**Comment by jplatte** [comment]
Thanks for the tip, language-cpp14 fixes user-defined literal highlighting. You can disable the default language-c package, then you don't need `-*- C++14 -*-`. It removes C highlighting though.

**Comment by fbbdev** [comment]
Any progress on this?

**Comment by alpyre** [comment]
```cpp
string normal_str="First.\"Second.\"Last.\"";
string raw_str=R"(First.\"Second.\"Last.\")";
```

I could not reproduce this issue. It is probably fixed already and may be closed.

**Comment by fbbdev** [comment]
@alpyre the issue regards syntax like this:
```c++
string raw_str = R"(First."Second."Last.")";
```

It doesn't happen with escaped quotes.

Anyway, I just tested this with atom v1.13.1 and it works correctly.
